sudo: required
services:
  - docker

# build test image
before_install:
  - docker build -f dockerfile.dev -t mtslimited/docker-react .

#test scripts
script:
  - docker run mtslimited/docker-react npm run test -- --coverage